New error mapping for submodule update errors.
bitrise-steplib/steps-git-clone pull request #130
Opened 2020-11-12 13:40 UTC by godrei

2020-11-12 15:24 UTC, zoltanszabo-bitrise requested changes

2020-11-12 15:24 UTC, zoltanszabo-bitrise commented on gitclone/steperror_test.go
> +	wantAuthenticationDeatiledError := func(errorMsg string) errormapper.DetailedError {
Typo:
`wantAuthenticationDeatiledError` -> `wantAuthenticationDetailedError`

2020-11-12 16:04 UTC, godrei commented on gitclone/steperror.go
> +Our auto-configurator returned the following error:
no, in case of a raw string literal `\n` will not be interpreted: https://golang.org/ref/spec#String_literals

2020-11-12 16:05 UTC, godrei commented on gitclone/steperror.go
> +func newUpdateSubmoduleFailedAuthenticationDetailedErrorBuilder(errorMsg string) errormapper.DetailedErrorBuilder {
i was thinking about that, i think it would be a cleaner solution, so I will do all the changes

2020-11-12 16:32 UTC, zoltanszabo-bitrise commented on gitclone/steperror.go
> +Our auto-configurator returned the following error:
And if you change it to an interpreted string? 😄

2020-11-17 13:15 UTC, zoltanszabo-bitrise approved these changes
LGTM 👍

2020-11-17 13:15 UTC, zoltanszabo-bitrise commented on gitclone/steperror.go
> +		matcher = newUpdateSubmoduleFailedErrorMatcher(errMsg)
I think this matcher doesn't need `errMsg` as input parameter anymore.

2020-11-17 13:27 UTC, merged