Clone step will not try to merge if there is commit or tag given
bitrise-steplib/steps-git-clone pull request #133
Opened 2020-12-08 12:26 UTC by mateherber

If commit or tag is given we check out them so we don't need to merge to
a branch with similar name

* Added test case

[STEP-36]

2020-12-08 12:35 UTC, adborbas submitted a review, later dismissed

2020-12-08 12:42 UTC, lpusok requested changes
There is branch == arg condition inside checkout(). When both tag and branch provided, it checks out the branch, not the tag. is it intended?

2020-12-08 13:14 UTC, mateherber commented
> There is branch == arg condition inside checkout(). When both tag and branch provided, it checks out the branch, not the tag. is it intended?

It involves the fetch only when both branch and tag will be fetched. The checkout will be `git checkout tag_branch_name` which will checkout the branch if it is present

2020-12-08 13:38 UTC, lpusok reviewed
discussed, lgtm

2020-12-08 13:38 UTC, lpusok submitted a review, later dismissed

2020-12-09 10:19 UTC, godrei approved these changes

2020-12-09 10:20 UTC, merged