Update workflows
bitrise-steplib/steps-git-clone pull request #163
Opened 2021-06-01 15:44 UTC by lpusok

### Context

### Changes

### Investigation details

### Decisions

2021-06-08 08:15 UTC, mateherber requested changes

2021-06-08 08:15 UTC, mateherber commented on bitrise.yml
> +    - SHOULD_ACTIVATE_SSH_KEY: true # Set to true to test with private repository
I wouldn't add configurability to the sample workflow. The test app URL is public so we don't need auth support. If you want to test it you should edit the sample wf as you see fit or use the e2e steps.

2021-06-08 08:15 UTC, mateherber commented on bitrise.yml
> +                echo "GIT_CLONE_COMMIT_HASH: ${GIT_CLONE_COMMIT_HASH}"
I wouldn't add this "validation" script either

2021-06-08 08:15 UTC, mateherber commented on e2e/bitrise.yml
> +  _assert_changelog:
I think this is a `_check_*` wf

2021-06-08 08:15 UTC, mateherber commented on e2e/bitrise.yml
> +  _log_outputs:
This is also a `_check_*` wf

2021-06-08 08:15 UTC, mateherber commented on e2e/bitrise.yml
> +  _prepare:
Probably we should have a naming convention for the `setup` kind of workflows too like `prepare` now. We might also have `teardown` kind of wfs like `_ensure_clean_git` now

I'm thinking like

```
test_*                  Test workflows
utility_*               Workflows that are used from tests
_check_*             Verify or print results
_setup_*             Prepare state for test
_teardown_*      Clean up state after test
```

2021-06-08 10:36 UTC, lpusok commented
> I wouldn't add this "validation" script either 

removed.

2021-06-08 10:36 UTC, lpusok commented
> This is also a `_check_*` wf 

Updated.

2021-06-08 11:12 UTC, mateherber commented on e2e/bitrise.yml
> +  _prepare:
You're right. Then I think we don't need the _setup/_teardown wfs just the _run but we will have to refactor this yml to that.

```
test_*                  Test workflows (prepare env vars for _run basically)
utility_*               Workflows that are used from tests
_check_*             Verify or print results
_run                    3 phase of step execution: setup, run the step, teardown
```

2021-06-08 11:14 UTC, mateherber commented on e2e/bitrise.yml
> +                #!/usr/bin/env bash
this should be extracted as check wf

2021-06-10 10:16 UTC, istvankovacs-bitrise approved these changes

2021-06-11 08:15 UTC, mateherber approved these changes

2021-06-11 08:15 UTC, merged